eventparser with test and ci report

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -14,7 +14,18 @@ jobs:
           fetch-depth: 0
 
       - name: Run test
-        run: make test
+        run: make test-report
+
+# https://github.com/jstemmer/go-junit-report
+# https://github.com/marketplace/actions/test-reporter
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()       # run this step even if previous step failed
+        with:
+          name: go-junit-report          # Name of the check run which will be created
+          path: go-junit-*.xml           # Path to test results
+          reporter: jest-junit           # Format of test results
+
       - name: Docker Hub Login
         uses: docker/login-action@v2
         with:
