Test Summary

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -13,17 +13,15 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: run tests
-        run: go test -json ./... > test.json
-
-      - name: Annotate tests
-        if: success() || failure()
-        uses: guyarb/golang-test-annotations@v0.6.0
-        with:
-          test-results: test.json
-
       - name: Run test
         run: make test-report
+
+      - name: Test Summary
+        if: success() || failure()       # run this step even if previous step faile
+        uses: test-summary/action@v1
+        with:
+          paths: |
+            go-junit-*.xml
 
       - name: Test Report
         # uses: dorny/test-reporter@v1 # default
@@ -34,6 +32,15 @@ jobs:
           path: go-junit-*.xml           # Path to test results
           reporter: jest-junit           # Format of test results
 
+      - name: run tests
+        if: success() || failure()
+        run: go test -json ./... > test.json
+
+      - name: Annotate tests
+        if: success() || failure()
+        uses: guyarb/golang-test-annotations@v0.6.0
+        with:
+          test-results: test.json
 
 
       - name: Docker Hub Login
