stacktrace-split-safe

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -16,15 +16,16 @@ jobs:
       - name: Run test
         run: make test-report
 
-      - name: workaround for report - ensure non-empty stack traces in failures
-        if: success() || failure()       # run this step even if previous step failed
-        run: >
-            sed -i
-            's#"></failure>#">No stack trace detected</failure>#g'
-            go-junit-report.xml 
-            ; cat go-junit-report.xml
+      # - name: workaround for report - ensure non-empty stack traces in failures
+      #   if: success() || failure()       # run this step even if previous step failed
+      #   run: >
+      #       sed -i
+      #       's#"></failure>#">No stack trace detected</failure>#g'
+      #       go-junit-report.xml 
+      #       ; cat go-junit-report.xml
       - name: Test Report
-        uses: dorny/test-reporter@v1
+        # uses: dorny/test-reporter@v1 # default
+        uses: moudrick/test-reporter@stacktrace-split-safe ## works, some blind fixes there
         if: success() || failure()       # run this step even if previous step failed
         with:
           name: go-junit-report          # Name of the check run which will be created
